import { ContentWMsg } from './ContentWMsg.js'

/**
 * Represents a generation message originating from the 'assistant' role.
 * Contains the response generated by the LLM.
 */
export class AssistantWMsg extends ContentWMsg {
    /**
     * Checks if a given object represents a valid assistant message JSON structure.
     *
     * @param {any} x The object to validate.
     * @returns {boolean} True if it is a valid assistant message representation, false otherwise.
     */
    static isAssistantMsgObj(x) {
        return super.isBaseMsgObj(x, 'assistant')
    }

    /**
     * Initializes a new AssistantWMsg.
     *
     * @param {...string} contents String parts that formulate the assistant's entire output content.
     */
    constructor(...contents) {
        super('assistant', ...contents)
    }
}
