import { isArr, isObj, isStr } from 'jty'
import { BaseWMsg } from './BaseWMsg.js'

/**
 * Describes a message from an assistant that includes tool call requests.
 * @typedef {object} ToolsCallMsgObj
 * @property {string} [content] - Optional textual content part of the message.
 * @property {'assistant'} role - The role of the message sender.
 * @property {ToolCallMsgObj[]} tool_calls - An array of tool calls requested by the assistant.
 */

/**
 * Describes a request from an LLM to call a specific tool function.
 * @typedef {object} ToolCallMsgObj
 * @property {string} id - A unique identifier for this tool call.
 * @property {'function'} type - The type of the call, always 'function'.
 * @property {object} function - The function to be called.
 * @property {string} function.name - The name of the function.
 * @property {string} function.arguments - A JSON string representing the arguments for the function.
 */

/**
 * Represents a system-generated message containing tool call execution requests.
 * Used when an assistant determines that an external function needs to be executed to proceed.
 */
export class ToolCallsWMsg extends BaseWMsg {
    /** @type {ToolCallMsgObj[]} */
    #toolCalls

    /**
     * Verifies if an object is a structurally valid ToolCallsWMsg representation.
     *
     * @param {any} x The object to validate.
     * @returns {boolean} True if the object matches the schema, false otherwise.
     */
    static isToolCallsMsgObj(x) {
        if (!super.isBaseMsgObj(x, 'assistant')) {
            return false
        }
        return isArr(x.toolCalls) && x.toolCalls.length > 0 && x.toolCalls.every(this.isToolCallObj)
    }

    /**
     * Validates an individual tool call object against the required structure.
     *
     * @param {any} x A single tool call object.
     * @returns {boolean} True if valid structurally, false otherwise.
     */
    static isToolCallObj(x) {
        if (!isObj(x)) {
            return false
        }
        // @ts-ignore
        return (
            // @ts-ignore
            isStr(x.id) &&
            // @ts-ignore
            x.type === 'function' &&
            // @ts-ignore
            isObj(x.function) &&
            // @ts-ignore
            isStr(x.function.name) &&
            // @ts-ignore
            isStr(x.function.arguments)
        )
    }

    /**
     * Initializes a new wrapper for tool call requests.
     *
     * @param {ToolCallMsgObj[]} toolCalls The array of tool call requests generated by the LLM.
     */
    constructor(toolCalls) {
        super('assistant')
        this.toolCalls = toolCalls
    }

    /**
     * Retrieves the array of pending tool call requests.
     * @returns {ToolCallMsgObj[]} The array of tool calls.
     */
    get toolCalls() {
        return this.#toolCalls
    }

    /**
     * Sets the internal array of tool calls. Ensures validation on each element.
     *
     * @param {ToolCallMsgObj[]} toolCalls The array of specific tool calls.
     * @throws {TypeError|RangeError} If the format or length is invalid.
     */
    set toolCalls(toolCalls) {
        if (!isArr(toolCalls)) {
            throw new TypeError('toolCalls must be an array')
        }
        if (toolCalls.length === 0) {
            throw new RangeError('toolCalls must be a non-empty array')
        }
        for (const toolCall of toolCalls) {
            if (!ToolCallsWMsg.isToolCallObj(toolCall)) {
                throw new TypeError(`toolCalls must be an array of tool calls. Got ${toolCall} (${typeof toolCall})`)
            }
        }
        this.#toolCalls = toolCalls
    }

    /**
     * Casts the message instance back into a JSON-compatible generic API format.
     * Converts the internal `toolCalls` key to `tool_calls`.
     *
     * @returns {{role: string, tool_calls: ToolCallMsgObj[]}}
     */
    toJSON() {
        const { role, toolCalls } = this
        return { role, tool_calls: toolCalls }
    }
}
