import { isStr } from 'jty'
import { ContentWMsg } from './ContentWMsg.js'

/**
 * Creates a tool result message object.
 * @param {string} id - The ID of the tool call.
 * @param {string} content - The result content from the tool execution.
 * @returns {{role: string, tool_call_id: string, content: string}} The constructed tool result message.
 */
export function toolResultMessage(id, content) {
    return {
        role: 'tool',
        tool_call_id: id,
        content,
    }
}

/**
 * Represents a message containing the execution results of a previously requested tool call.
 */
export class ToolResultWMsg extends ContentWMsg {
    /** @type {string} */
    #toolCallId

    /**
     * Checks if a given object represents a valid tool result message structure.
     *
     * @param {any} x The object to validate.
     * @returns {boolean} True if it is a valid tool result message representation, false otherwise.
     */
    static isToolResultMsgObj(x) {
        if (!super.isBaseMsgObj(x, 'tool')) {
            return false
        }
        // @ts-ignore
        return isStr(x.tool_call_id) && isStr(x.content)
    }

    /**
     * Initializes a new message delivering the outcome of a tool execution.
     *
     * @param {string} toolCallId The ID connecting this result to the original tool request.
     * @param {string|object} result The data generated by the tool. Non-strings will be serialized to JSON.
     */
    constructor(toolCallId, result) {
        super('tool')
        this.toolCallId = toolCallId
        this.content = isStr(result) ? result : JSON.stringify(result)
    }

    /**
     * Returns the associated request ID for this execution result.
     * @returns {string} The original requested tool call ID.
     */
    get toolCallId() {
        return this.#toolCallId
    }

    /**
     * Sets the associated ID linking this message to the tool execution request.
     *
     * @param {string} toolCallId The target tool call ID.
     * @throws {TypeError} If the ID is not properly formatted as a string.
     */
    set toolCallId(toolCallId) {
        if (!isStr(toolCallId)) {
            throw new TypeError('toolCallId must be a string')
        }
        this.#toolCallId = toolCallId
    }

    /**
     * Prepares this wrapper instance to be serialized into a standard OpenAI JSON format.
     *
     * @returns {{role: string, tool_call_id: string, content: string}} The plain-object output.
     */
    toJSON() {
        return {
            role: this.role,
            tool_call_id: this.#toolCallId,
            content: this.content,
        }
    }
}
